If No Interface is Up During Config Set Local Ip Wildcard
If the local IP address cannot be determined, set the bind interface to
0.0.0.0 and ask for the public address manually.

diff --git a/dmc-access-mgr b/dmc-access-mgr
--- a/dmc-access-mgr
+++ b/dmc-access-mgr
@@ -1207,15 +1207,20 @@ if [[ ! -e ${SERVERDIR}/server.conf ]]; then
         else
             number_of_ip=$(ip -4 addr | grep inet | grep -vEc '127(\.[0-9]{1,3}){3}')
             echo
-            echo "Which IPv4 address should be used?"
-            ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | nl -s ') '
-            read -p "IPv4 address [1]: " ip_number
-            until [[ -z "$ip_number" || "$ip_number" =~ ^[0-9]+$ && "$ip_number" -le "$number_of_ip" ]]; do
-                echo "$ip_number: invalid selection."
+            if [ $number_of_ip -eq 0 ] ; then
+                >&2 echo "warning: no interface is connected so server will be bound to all interfaces"
+                address=0.0.0.0
+            else
+                echo "Which IPv4 address should be used?"
+                ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | nl -s ') '
                 read -p "IPv4 address [1]: " ip_number
-            done
-            [[ -z "$ip_number" ]] && ip_number="1"
-            address=$(ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | sed -n "$ip_number"p)
+                until [[ -z "$ip_number" || "$ip_number" =~ ^[0-9]+$ && "$ip_number" -le "$number_of_ip" ]]; do
+                    echo "$ip_number: invalid selection."
+                    read -p "IPv4 address [1]: " ip_number
+                done
+                [[ -z "$ip_number" ]] && ip_number="1"
+                address=$(ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | sed -n "$ip_number"p)
+            fi
         fi
     fi
     if [ -z "$public_address" ] ; then
@@ -1232,6 +1237,14 @@ if [[ ! -e ${SERVERDIR}/server.conf ]]; then
                 read -p "Public IPv4 address / hostname: " public_address
             done
             [[ -z "$public_address" ]] && public_address="$get_public_address"
+        fi
+        if [ $address == '0.0.0.0' ] ; then
+            while : ; do
+                public_address=$(ipv4address_get "At what public IP address will this server be reachable?")
+                if [ -n "$public_address" ] ; then
+                    break
+                fi
+            done
         fi
     fi
 
