We Can Not Use the 0.0.0.0 Interface for Binding
Packets have to be routed to the local IP in the firewall, so using the
wildcard does not work. Ask for the static address manually instead.

diff --git a/dmc-access-mgr b/dmc-access-mgr
--- a/dmc-access-mgr
+++ b/dmc-access-mgr
@@ -1182,7 +1182,7 @@ if [[ ! -e ${SERVERDIR}/server.conf ]]; then
             echo "    interfaces 3 and 4 should be connected to the DMC"
             wanif='enp1s0'
             mgmtif="enp2s0"
-            lanifs="enp3s0 enp4s0"
+            lanifs="enp3s0,enp4s0"
         else
             [ -z "$wanif" ] && select_wanif
             [ -z "$mgmtif" ] && select_mgmtif
@@ -1208,8 +1208,13 @@ if [[ ! -e ${SERVERDIR}/server.conf ]]; then
             number_of_ip=$(ip -4 addr | grep inet | grep -vEc '127(\.[0-9]{1,3}){3}')
             echo
             if [ $number_of_ip -eq 0 ] ; then
-                >&2 echo "warning: no interface is connected so server will be bound to all interfaces"
-                address=0.0.0.0
+                >&2 echo "warning: no interface is connected, manually enter the IP address that will be assigned to $wanif"
+                while : ; do
+                    address=$(ipv4address_get "What is the IP address of WAN port $wanif?")
+                    if [ -n "$address" ] ; then
+                        break
+                    fi
+                done
             else
                 echo "Which IPv4 address should be used?"
                 ip -4 addr | grep inet | grep -vE '127(\.[0-9]{1,3}){3}' | cut -d '/' -f 1 | grep -oE '[0-9]{1,3}(\.[0-9]{1,3}){3}' | nl -s ') '
@@ -1228,23 +1233,24 @@ if [[ ! -e ${SERVERDIR}/server.conf ]]; then
         if echo "$address" | grep -qE '^(10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.|192\.168)'; then
             echo
             echo "This server is behind NAT. What is the public IPv4 address or hostname?"
-            # Get public IP and sanitize with grep
-            get_public_address=$(grep -m 1 -oE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' <<< "$(wget -T 10 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/" || curl -m 10 -4Ls "http://ip1.dynupdate.no-ip.com/")")
-            read -p "Public IPv4 address / hostname [$get_public_address]: " public_address
-            # If the checkip service is unavailable and user did not provide input, ask again
-            until [[ -n "$get_public_address" || -n "$public_address" ]]; do
-                echo "Invalid input."
-                read -p "Public IPv4 address / hostname: " public_address
-            done
-            [[ -z "$public_address" ]] && public_address="$get_public_address"
-        fi
-        if [ $address == '0.0.0.0' ] ; then
-            while : ; do
-                public_address=$(ipv4address_get "At what public IP address will this server be reachable?")
-                if [ -n "$public_address" ] ; then
-                    break
-                fi
-            done
+            if [ $number_of_ip -eq 0 ] ; then
+                while : ; do
+                    public_address=$(ipv4address_get "At what public IP address will this server be reachable?")
+                    if [ -n "$public_address" ] ; then
+                        break
+                    fi
+                done
+            else
+                # Get public IP and sanitize with grep
+                get_public_address=$(grep -m 1 -oE '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' <<< "$(wget -T 10 -t 1 -4qO- "http://ip1.dynupdate.no-ip.com/" || curl -m 10 -4Ls "http://ip1.dynupdate.no-ip.com/")")
+                read -p "Public IPv4 address / hostname [$get_public_address]: " public_address
+                # If the checkip service is unavailable and user did not provide input, ask again
+                until [[ -n "$get_public_address" || -n "$public_address" ]]; do
+                    echo "Invalid input."
+                    read -p "Public IPv4 address / hostname: " public_address
+                done
+                [[ -z "$public_address" ]] && public_address="$get_public_address"
+            fi
         fi
     fi
 
@@ -1291,6 +1297,7 @@ if [[ ! -e ${SERVERDIR}/server.conf ]]; then
 
     VPNSERVER=$(ipcalc -nb ${VPNNET} | awk '/^Address:/{printf "%s ", $2}; /^Netmask:/{print $2}')
 
+    cd ${SERVERDIR}/easy-rsa/
     # Create the PKI, set up the CA and the server and client certificates
     ./easyrsa init-pki
     ./easyrsa --batch build-ca nopass
